export enum NOTIFICATION_TYPE {
  ATTACHMENT = 'Attachment',
  PAYMENT = 'Payment',
  PENALTY = 'Penalty',
  MESSAGE = 'Message',
  CREDITS_GIFTED = 'Credits Gifted',
  CONTACT_SUPPORT = 'Contact & Support',
  BOOKING_STATUS = 'Booking Status',
  SERVICE_STATUS = 'Service Status',
  EDIT_PROVIDER = 'Edit Request from Provider',
  EDIT_PROVIDER_APPROVED = 'Edit Request Approved',
  PROVIDER_APPROVED = 'Provider Approved',
  NEW_PROVIDER = 'New Provider Registered',
  REVIEW = 'New Review',
  SETTINGS = 'Settings',
}
